name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main  # Change this to your source code branch, e.g., `master` or `main`

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0' # Specify Ruby version here

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # Use your Personal Access Token (PAT)
          ssh_private_key: ''        # Your SSH private key (if using SSH approach)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: ''            # Specify if you want a specific Bundler version, else it uses a compatible version
          cname: ''                  # Use a CNAME (Custom domain) if needed
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Use this to install additional dependencies
